### ISSUE TITLE
Il faut faire les templates HTML:login,multivue,result,file,home,user,revise

### ISSUE THREAD

**Issue by ArthurVillette** [Nathan-Etave/PinPon45#19]
Il faut faire les différentes templates web nécessaires aux vues HTML.

login: la page de connexion
multivue: la page pour les multiples vues
result: la page des fichiers recherchés
file: la page  du fichier recherché
home: page d'accueil
user: page de profils utilisateur
revise: page de modification utilisateur

**Comment by RomainMechain** [comment]
Très bien, je vais m'occuper de la page home.

**Comment by Nathan-Etave** [comment]
J'ai fait la page baseUser.

**Comment by ArthurVillette** [comment]
je fais connection

**Comment by Nathan-Etave** [comment]
J'ai fait la page ```file``` (HTML + CSS + JS).

**Comment by RomainMechain** [comment]
J'ai fini la page home, une merge request est en attente, je reprendrais si il y a besoin de modifier certaine chose. Je commence donc la page search.

**Comment by ArthurVillette** [comment]
connexion fais
