### ISSUE TITLE
Fix la table NOTIFICATION et A_NOTIFICATION dans la BD

### ISSUE THREAD

**Issue by RomainMechain** [Nathan-Etave/PinPon45#26]
Dans la base de donnée, ajoute à la table NOTIFICATION les attributs : 
- typeChangementNotification
- raisonNotification
Il faut aussi ajouter un lien entre A_NOTIFICATION et les tables : 
- FICHIER
- DATE
Il y a donc des modifications à faire dans le MCD/MLD ainsi que dans le script SQL

**Comment by ArthurVillette** [comment]
ok ça marche
