### ISSUE TITLE
Faire le script de la base de données. 

### ISSUE THREAD

**Issue by RomainMechain** [Nathan-Etave/PinPon45#3]
Pour faire le script, il faut partir du MCD et MLD fait au préalable. Il sera séparé en plusieurs fichiés : 
- create_tables.sql : Le fichier de création des tables 
- drop_tables.sql : Le script permettant de supprimé toute les tables de la base de données 
- clear_tables.sql : LE script qui permet de supprimé toutes les inforations de la base de données 
Faite des vérifications pour chaque fichier.

**Comment by ArthurVillette** [comment]
les scripts on été crée en attente des inserts

**Comment by RomainMechain** [comment]
Les fichiers demandés ont été fait et merge dans la branche de développement.
