### ISSUE TITLE
Développement du Module Administrateur

### ISSUE THREAD

**Issue by Norikokonut** [Nathan-Etave/PinPon45#30]
Développer les vues pour le module administrateur

Ce module comprend les pages :
- Gestion admin : Page permettant d'acceder à toutes les autres page 
- Recherche Utilisateur : Page pour rechercher un utilisateur en fonction de son id, son email ou son nom/prénom
- Recherche Catégorie : Page pour rechercher un rôle par son nom ( page permettant aussi d'en supprimer )
- Recherche Rôle : Page pour rechercher un rôle par son nom ( page permettant aussi d'en supprimer )
- Ajout / Modif fichier : Page de modification ou d'ajout d'un fichier
- Ajout Catégorie : Page d'ajout d'une catégorie
- Ajout / Modif Rôle : Page de modification des droits ou d'ajout d'une catégorie

**Comment by ArthurVillette** [comment]
j'ai fais la page d'acceuil

**Comment by Norikokonut** [comment]
Enfin fini
