### ISSUE TITLE
fix la BD

### ISSUE THREAD

**Issue by ArthurVillette** [Nathan-Etave/PinPon45#32]
il faut ajouter une table de lien entre les tables CATEGORIE et ROLE

**Comment by RomainMechain** [comment]
Je m'en occupe je vais modifier cela sur la documentation et les scripts

**Comment by RomainMechain** [comment]
Je viens de finir la documentation, je vais m'occuper du script.

**Comment by RomainMechain** [comment]
Le script a été corrigé et la branche a bien été merge dans feature/table_BD.
