### ISSUE TITLE
Faire les components web.

### ISSUE THREAD

**Issue by Nathan-Etave** [Nathan-Etave/PinPon45#4]
Il faut faire les différents components web nécessaires aux templates HTML :

- header.html : l'header de toutes les templates.
- footer.html : le footer de toutes les templates.
- bottomHeader.html : la barre inférieure au header avec seulement le titre et la localisation actuelle. 
- bottomHeaderSearchBar.html : la barre inférieure au header avec le titre, la localisation actuelle et la barre de recherche.
- bottomSearchBar.html : la barre inférieure au header avec seulement la barre de recherche.
- ...

**Comment by ArthurVillette** [comment]
les components on été fais par l'équipes
