### ISSUE TITLE
Fix des diagrammes UML

### ISSUE THREAD

**Issue by RomainMechain** [Nathan-Etave/PinPon45#5]
Nous venons d'avoir de nouvelles informations des clients sur les besoins de l'application web, pour cela nous devons modifier nos diagrammes : 
- Diagramme de cas d'utilisation simple : Ajouter pour les administrateur le fait de gérer les rôles et les catégories
- Diagramme de cas d'utilisation complet : detailler les cas precèdent

**Comment by ArthurVillette** [comment]
l'équipe a corriger les diagrammes selons la demande clien

**Comment by Nathan-Etave** [comment]
Il faut faire les descriptions textuelles des cas d'utilisations du diagramme de cas d'utilisations simple.

**Comment by ArthurVillette** [comment]
ok

**Comment by Nathan-Etave** [comment]
La documentation est de nouveaux à jour. #17
