### ISSUE TITLE
Fonctionnalité de signalement en BD

### ISSUE THREAD

**Issue by RomainMechain** [Nathan-Etave/PinPon45#58]
La fonctionnalité de signalement des fichiers est à finalisé. 
- Corriger la possibiliter de les supprimer 
- Faire un sorte qu'un signalement ajoute le message à la BD

**Comment by Nathan-Etave** [comment]
Nous (@LouisL18 ) avons push sur la branche feature/file_report la fonctionnalité corrigée.
