### ISSUE TITLE
Historique fichiers consulté 

### ISSUE THREAD

**Issue by RomainMechain** [Nathan-Etave/PinPon45#59]
Il faut ajouter la possibilité de consulter les fichiers récement consulté, il faut donc faire : 
- Un trie par date de consultation 
- Ajouter dans la BD chaque fois qu'une consultation est faite

**Comment by Nathan-Etave** [comment]
J'ai push sur la branche feature/a_consulte l'ajout d'une consultation dans la BD à chaque fois qu'un utilisateur consulte un fichier.

**Comment by RomainMechain** [comment]
La consultation des fichiers en fonction de la date de consultation est possible.
