### ISSUE TITLE
Fix de la branche Flask 

### ISSUE THREAD

**Issue by RomainMechain** [Nathan-Etave/PinPon45#78]
Il faut apporter les corrections suivantes : 
- Ajouter la route vers administration OK
- Ajouter la route vers editRole OK
- Ajouter le bouton Admin dans le header OK
- Ajouter la fonction manquante dans request (get_all_role() ) OK
- Ajouter le headerBotom dans administration OK
- Ajouter dans condition pour modifier et supprimer dans la multivue OK
- Href administration edit_categories OK
- Menu burger téléphone
- ...

**Comment by Nathan-Etave** [comment]
Il faut également :
- CSS de edit_user
- is_admin sur toutes les routes

**Comment by RomainMechain** [comment]
Les erreurs indiqués dans l'issue ont bien été corrigé.
