### ISSUE TITLE
Derniers fix à régler 

### ISSUE THREAD

**Issue by RomainMechain** [Nathan-Etave/PinPon45#87]
Voici la liste des derniers fix à faire : 
- ~~La cloche qui bouge sur téléphone même si il n'y a plus de notification Nathan OK~~
-   ~~la pop-up de recherche n'est pas responsive~~
- ~~finaliser la page de gestion des rôles~~
- ~~rendre responsive la page de gestion des fichiers  --> Hugo et Louis~~
- ~~rendre responsive la page de gestion des utilisateurs -->Hugo & Nathan~~
- ~~gérer le cas ou il y a plusieurs personne avec le même nom dans la recherche par nom~~
- ~~refaire le menu bouton sur téléphone~~ 
-  ~~rendre responsive la gestion des catégories~~
- ~~rendre responsive la page de gestion des rôles~~

**Comment by Nathan-Etave** [comment]
- téléchargement dans la multivue

**Comment by ArthurVillette** [comment]
je m'occupe de la pop-up de recherche responsive ce matin

**Comment by ArthurVillette** [comment]
page pop-up ok

**Comment by Nathan-Etave** [comment]
téléchargement dans la multivue OK

**Comment by Nathan-Etave** [comment]
La cloche qui bouge sur téléphone même si il n'y a plus de notification OK

**Comment by RomainMechain** [comment]
J'ai mis un message d'erreur si il y a plusieurs personnes avec le même nom/prenom lors de la recherche d'utilisateur.

**Comment by Nathan-Etave** [comment]
J'ai régler le problème quand on supprime une categorie mère et qu'un fichier est dans deux de ses sous-categories, cela ne trigger pas la condition de len == 0 et ce qui fait crash l'app car le fichier se retrouve donc dans une catégorie qui n'existe plus. OK

**Comment by Nathan-Etave** [comment]
Les nombres de fichiers affichés dans les arbres de catégorie ne sont pas cohérents.OK

**Comment by RomainMechain** [comment]
Tout les fix ont bien été réglé.
